version: '3'
services:
  # only used for development:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/app