version: "3.8"

x-common-variables: &common-variables
  POSTGRES: postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=300
  POSTGRES_COLLAB: postgresql://postgres:postgres@postgres-collab:5432/postgres?connect_timeout=300
  MONGO: mongodb://user:password@mongo:27017
  EXE_ENV: DEV
  JWT_SECRET: EXAMPLE_SECRERT # pass around JWT secret so each service can verify user TODO: add to github secrets on deployment
  REFRESH_COOKIE_KEY: EXAMPLE_PEERPREPREFRESHTOKEN
  ACCESS_COOKIE_KEY: EXAMPLE_PEERPREPACCESSTOKEN
  SERVER_PORT: 3000

networks:
  frontend:
  backend:

services:
  user:
    container_name: user
    build:
      dockerfile: ./microservices/user/Dockerfile.local
      context: ./backend
    volumes:
      - ./backend/microservices/user:/home/microservices/user/
      - /home/microservices/user/node_modules
    ports:
      - 8080:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables

  question:
    container_name: question
    build:
      dockerfile: ./microservices/question/Dockerfile.local
      context: ./backend
    volumes:
      - ./backend/microservices/question:/home/microservices/question/
      - /home/microservices/question/node_modules
    ports:
      - 3001:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables

  collaboration:
    container_name: collaboration
    build:
      dockerfile: ./microservices/collaboration/Dockerfile.local
      context: ./backend
    volumes:
      - ./backend/microservices/collaboration:/home/microservices/collaboration/
      - /home/microservices/collaboration/node_modules
    ports:
      - 5001:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables
      SERVER_PORT: 3000

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  postgres-collab:
    container_name: postgres-collab
    build:
      context: ./postgres-collab
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-collab:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Use a different port for the new instance, e.g., 5433
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - backend

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL="mongo://user:password@mongo:27017/"
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - backend

  matching:
    container_name: matching
    build:
      dockerfile: ./microservices/matching/Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend/microservices/matching:/home/microservices/matching/
      - /home/microservices/matching/node_modules
    ports:
      - 7001:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables
      GOOGLE_APPLICATION_CREDENTIALS: "/home/microservices/matching/key.json"
      COLLAB_SERVICE_ENDPOINT: "http://nginx:80/collaboration"
      MATCHING_REQUEST_REDIS_URL: rediss://default:e840999abd7046a39bf40c6aaf69faf9@quality-llama-43887.upstash.io:43887
      MATCHING_PAIR_REDIS_URL: rediss://default:9ed22128c2b945b78ff7fd840679a80a@sought-meerkat-43858.upstash.io:43858

  nginx:
    depends_on:
      - client
      - user
      - matching
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - backend
      - frontend

  client:
    build:
      dockerfile: Dockerfile.local
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json

volumes:
  postgres:
  postgres-collab:
  mongo:
