apiVersion: v1
kind: Service
metadata:
  name: collaboration
  labels:
    app: collaboration
spec:
  ports:
    - name: http
      port: 80          
      targetPort: 3000  
  selector:
    app: collaboration
  type: ClusterIP