apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"peerprep-backendconfig"}}'
  name: document-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
      - name: document
        image: asia-southeast1-docker.pkg.dev/cs3219-402414/peerprepimages/document:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: global-config
        - configMapRef:
            name: document-config
        resources:
          requests:
            cpu: "250m" 
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"