apiVersion: v1
kind: Service
metadata:
  name: question
  labels:
    app: question
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3000
  selector:
    app: question
  type: ClusterIP
